name: task_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_riverpod: ^2.3.6
  path_provider: ^2.0.14
  flutter_bloc: ^8.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3   
  intl: ^0.18.0
  table_calendar: ^3.0.9
  isar_generator: ^3.1.0+1
flutter:
  uses-material-design: true
